version: "3"
services:
  bms_api:
    build: .
    depends_on:
      - bms_postgres
    environment:
      DATABASE_URL: postgres://user:pass@bms_postgres:5432/bms
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app/
    command: bash -c "npm run migrate up && npm run dev"

  bms_postgres:
    image: 'postgres-13.3'
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: bms

volumes:
  pgdata: